// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_google from "./routes/api/google.ts";
import * as $api_lang from "./routes/api/lang.ts";
import * as $bill_printing from "./routes/bill-printing.tsx";
import * as $index from "./routes/index.tsx";
import * as $orders from "./routes/orders.tsx";
import * as $Dashboard from "./islands/Dashboard.tsx";
import * as $DynamicManifest from "./islands/DynamicManifest.tsx";
import * as $KittyPrinter from "./islands/KittyPrinter.tsx";
import * as $Nav from "./islands/Nav.tsx";
import * as $OrderManagement from "./islands/OrderManagement.tsx";
import * as $PwaUpdate from "./islands/PwaUpdate.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/google.ts": $api_google,
    "./routes/api/lang.ts": $api_lang,
    "./routes/bill-printing.tsx": $bill_printing,
    "./routes/index.tsx": $index,
    "./routes/orders.tsx": $orders,
  },
  islands: {
    "./islands/Dashboard.tsx": $Dashboard,
    "./islands/DynamicManifest.tsx": $DynamicManifest,
    "./islands/KittyPrinter.tsx": $KittyPrinter,
    "./islands/Nav.tsx": $Nav,
    "./islands/OrderManagement.tsx": $OrderManagement,
    "./islands/PwaUpdate.tsx": $PwaUpdate,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
